version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        "VARIANT": "buster"
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh:/home/vscode/.ssh
    command: sleep infinity
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
volumes:
  db_volume:
